import { createClient } from '../supabase/client';
import { Order, OrderStatus, PaymentStatus, InvoiceData } from '@/store/orders.store';

export const ordersApi = {
  async createOrder(data: Partial<Order>) {
    const supabase = createClient();
    const { items, ...orderData } = data;

    // 1. Insert order (order_number is generated by DB trigger)
    const { data: order, error: orderError } = await supabase
      .from('orders')
      .insert([
        {
          customer_id: orderData.customer_id,
          is_registered_customer: !!orderData.customer_id,
          guest_first_name: orderData.guest_first_name,
          guest_last_name: orderData.guest_last_name,
          guest_phone: orderData.guest_phone,
          guest_wilaya: orderData.guest_wilaya,
          guest_commune: orderData.guest_commune,
          total_amount: orderData.total_amount,
          amount_paid: 0,
          payment_status: 'unpaid',
          order_status: 'pending',
          admin_notes: '',
        },
      ])
      .select()
      .single();

    if (orderError) throw orderError;

    // 2. Insert order items
    if (items && items.length > 0) {
      const { error: itemsError } = await supabase.from('order_items').insert(
        items.map((item) => ({
          order_id: order.id,
          product_id: item.product_id,
          product_type: item.product_type,
          product_name_fr: item.product_name_fr,
          product_name_ar: item.product_name_ar,
          flacon_variant_id: item.flacon_variant_id,
          variant_label: item.variant_label,
          unit_price: item.unit_price,
          quantity_grams: item.quantity_grams,
          quantity_units: item.quantity_units,
          total_price: item.total_price,
        }))
      );

      if (itemsError) throw itemsError;
    }

    // 3. Log initial status
    await supabase.from('order_status_history').insert([
      {
        order_id: order.id,
        status: 'pending',
        note: 'Order placed',
      },
    ]);

    return order;
  },

  async fetchOrdersByCustomer(customerId: string) {
    const supabase = createClient();
    const { data, error } = await supabase
      .from('orders')
      .select(`
        *,
        items:order_items(*),
        status_history:order_status_history(*)
      `)
      .eq('customer_id', customerId)
      .order('created_at', { ascending: false });

    if (error) throw error;
    return data as Order[];
  },

  async fetchAllOrders() {
    const supabase = createClient();
    const { data, error } = await supabase
      .from('orders')
      .select(`
        *,
        items:order_items(*),
        status_history:order_status_history(*)
      `)
      .order('created_at', { ascending: false });

    if (error) throw error;
    return data as Order[];
  },

  async updateOrderStatus(id: string, status: OrderStatus, note?: string) {
    const supabase = createClient();
    
    // 1. Update order status
    const { error: orderError } = await supabase
      .from('orders')
      .update({ order_status: status })
      .eq('id', id);

    if (orderError) throw orderError;

    // 2. Add to history
    const { error: historyError } = await supabase
      .from('order_status_history')
      .insert([{ order_id: id, status, note }]);

    if (historyError) throw historyError;
  },

  async updateOrderPayment(id: string, amountPaid: number) {
    const supabase = createClient();
    
    // Fetch order to check total
    const { data: order, error: fetchError } = await supabase
      .from('orders')
      .select('total_amount')
      .eq('id', id)
      .single();
    
    if (fetchError) throw fetchError;

    const paymentStatus: PaymentStatus =
      amountPaid <= 0 ? 'unpaid' : amountPaid >= order.total_amount ? 'paid' : 'partial';

    const { error: updateError } = await supabase
      .from('orders')
      .update({ amount_paid: amountPaid, payment_status: paymentStatus })
      .eq('id', id);

    if (updateError) throw updateError;
  },

  async updateAdminNotes(id: string, notes: string) {
    const supabase = createClient();
    const { error } = await supabase
      .from('orders')
      .update({ admin_notes: notes })
      .eq('id', id);
    
    if (error) throw error;
  },

  async generateInvoice(orderId: string, invoiceData: InvoiceData) {
    const supabase = createClient();
    const { error } = await supabase
      .from('orders')
      .update({
        invoice_generated: true,
        invoice_number: invoiceData.invoice_number,
        invoice_data: invoiceData as any,
      })
      .eq('id', orderId);

    if (error) throw error;
  }
};
