import { Category, Brand, Collection, Tag, Product, Customer, Order } from './types';

export const categories: Category[] = [
  { id: 'c1', nameAR: 'عود', nameFR: 'Oud', image: 'https://images.unsplash.com/photo-1546190255-451a91afc548?q=80&w=800' },
  { id: 'c2', nameAR: 'زهري', nameFR: 'Floral', image: 'https://images.unsplash.com/photo-1592914610354-fd354ea45e48?q=80&w=800' },
  { id: 'c3', nameAR: 'شرقي', nameFR: 'Oriental', image: 'https://images.unsplash.com/photo-1512201066733-1ec72ac9041f?q=80&w=800' },
  { id: 'c4', nameAR: 'منعش', nameFR: 'Frais', image: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?q=80&w=800' },
  { id: 'c5', nameAR: 'خشبي', nameFR: 'Boisé', image: 'https://images.unsplash.com/photo-1550928431-ee0ec6db30d3?q=80&w=800' },
];

export const brands: Brand[] = [
  { id: 'b1', nameAR: 'الحرمين', nameFR: 'Al Haramain', logo: '/images/brands/al-haramain.jpg' },
  { id: 'b2', nameAR: 'عمواج', nameFR: 'Amouage', logo: '/images/brands/amouage.jpg' },
  { id: 'b3', nameAR: 'لطافة', nameFR: 'Lattafa', logo: '/images/brands/lattafa.jpg' },
  { id: 'b4', nameAR: 'ميزون طهارة', nameFR: 'Maison Tahara', logo: '/images/brands/maison-tahara.jpg' },
  { id: 'b5', nameAR: 'رصاصي', nameFR: 'Rasasi', logo: '/images/brands/rasasi.jpg' },
  { id: 'b6', nameAR: 'سويس أربيان', nameFR: 'Swiss Arabian', logo: '/images/brands/swiss-arabian.jpg' },
];

export const collections: Collection[] = [
  { id: 'col1', nameAR: 'المجموعة الملكية', nameFR: 'Collection Royale' },
  { id: 'col2', nameAR: 'الصيف العربي', nameFR: 'Été Arabe' },
  { id: 'col3', nameAR: 'ليلة الصحراء', nameFR: 'Nuit de Sahara' },
  { id: 'col4', nameAR: 'بريستيج', nameFR: 'Prestige' },
];

export const tags: Tag[] = [
  { id: 't1', nameAR: 'وصل جديد', nameFR: 'Arrivage', showOnHomepage: true },
  { id: 't2', nameAR: 'الأكثر مبيعاً', nameFR: 'Best-seller', showOnHomepage: true },
  { id: 't3', nameAR: 'مميز', nameFR: 'Premium', showOnHomepage: true },
  { id: 't4', nameAR: 'عرض خاص', nameFR: 'Offre spéciale', showOnHomepage: false },
  { id: 't5', nameAR: 'حصري', nameFR: 'Exclusif', showOnHomepage: false },
  { id: 't6', nameAR: 'موسمي', nameFR: 'Saisonnier', showOnHomepage: false },
];

export const products: Product[] = [
  // PARFUMS
  {
    id: 'p1',
    type: 'perfume',
    nameFR: 'Rose du Taif',
    nameAR: 'وردة الطائف',
    descriptionFR: 'Une huile de parfum envoûtante aux notes de rose de Taïf, oud blanc et musc rare.',
    descriptionAR: 'زيت عطري فاتن بنفحات وردة الطائف والعود الأبيض والمسك النادر.',
    categoryId: 'c2',
    brandId: 'b1',
    collectionId: 'col1',
    tagIds: ['t1', 't2'],
    pricePerGram: 850,
    stockInGrams: 5000,
    images: ['https://images.unsplash.com/photo-1594035910387-fea477262dc0?q=80&w=800'],
    status: 'active',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p2',
    type: 'perfume',
    nameFR: 'Oud Malaki',
    nameAR: 'عود ملكي',
    descriptionFR: 'L\'oud royal dans toute sa splendeur. Profond, chaleureux, impérial.',
    descriptionAR: 'العود الملكي في كامل روعته. عميق، دافئ، فاخر.',
    categoryId: 'c1',
    brandId: 'b2',
    collectionId: 'col1',
    tagIds: ['t2', 't3'],
    pricePerGram: 1200,
    stockInGrams: 3000,
    images: ['https://images.unsplash.com/photo-1546190255-451a91afc548?q=80&w=800'],
    status: 'active',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p3',
    type: 'perfume',
    nameFR: 'Jasmin Sauvage',
    nameAR: 'ياسمين بري',
    descriptionFR: 'Jasmin blanc intense capturé à l\'aurore. Frais, floral, addictif.',
    descriptionAR: 'ياسمين أبيض مكثف يُقطف عند الفجر. منعش، زهري، مُدمِن.',
    categoryId: 'c2',
    brandId: 'b4',
    collectionId: 'col2',
    tagIds: ['t1'],
    pricePerGram: 650,
    stockInGrams: 4500,
    images: ['https://images.unsplash.com/photo-1616984748472-de362243dccd?q=80&w=800'],
    status: 'active',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p4',
    type: 'perfume',
    nameFR: 'Ambre Noir',
    nameAR: 'عنبر أسود',
    descriptionFR: 'Un amber mystérieux aux accords de bois précieux et de vanille noire.',
    descriptionAR: 'عنبر غامض بمزيج الأخشاب النفيسة والفانيلا السوداء.',
    categoryId: 'c3',
    brandId: 'b5',
    collectionId: 'col3',
    tagIds: ['t3'],
    pricePerGram: 950,
    stockInGrams: 2500,
    images: ['https://images.unsplash.com/photo-1615484477778-ca3b77940c25?q=80&w=800'],
    status: 'active',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p5',
    type: 'perfume',
    nameFR: 'Musc Tahara',
    nameAR: 'مسك طهارة',
    descriptionFR: 'Musc blanc pur, délicat et soyeux. Une pureté absolue.',
    descriptionAR: 'مسك أبيض نقي، رقيق وحريري. نقاء مطلق.',
    categoryId: 'c4',
    brandId: 'b4',
    collectionId: 'col4',
    tagIds: ['t1', 't2'],
    pricePerGram: 500,
    stockInGrams: 6000,
    images: ['https://images.unsplash.com/photo-1590736704728-f4730bb30770?q=80&w=800'],
    status: 'active',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p6',
    type: 'perfume',
    nameFR: 'Bakhoor Al Majd',
    nameAR: 'بخور المجد',
    descriptionFR: 'L\'essence du bakhoor traditionnel en huile concentrée.',
    descriptionAR: 'جوهر البخور التقليدي في زيت مركّز. رحلة إلى قلب الشرق.',
    categoryId: 'c1',
    brandId: 'b1',
    collectionId: 'col3',
    tagIds: ['t3'],
    pricePerGram: 1100,
    stockInGrams: 2000,
    images: ['https://images.unsplash.com/photo-1613524673822-6b9409b33a04?q=80&w=800'],
    status: 'active',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p7',
    type: 'perfume',
    nameFR: 'Cedar & Iris',
    nameAR: 'سيدار وإيريس',
    descriptionFR: 'Cèdre du Liban et iris poudré. Élégance boisée intemporelle.',
    descriptionAR: 'أرز لبنان والإيريس المسحوق. أناقة خشبية خالدة.',
    categoryId: 'c5',
    brandId: 'b6',
    collectionId: 'col4',
    tagIds: ['t2'],
    pricePerGram: 780,
    stockInGrams: 3500,
    images: ['https://images.unsplash.com/photo-1595428774223-ef52624120d2?q=80&w=800'],
    status: 'active',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p8',
    type: 'perfume',
    nameFR: 'Nuit Orientale',
    nameAR: 'ليلة شرقية',
    descriptionFR: 'Épices chaudes, santal et oud fumé pour les nuits d\'exception.',
    descriptionAR: 'توابل دافئة وصندل وعود مدخن لليالي الاستثنائية.',
    categoryId: 'c3',
    brandId: 'b3',
    collectionId: 'col3',
    tagIds: ['t1', 't3'],
    pricePerGram: 1050,
    stockInGrams: 1800,
    images: ['https://images.unsplash.com/photo-1547887538-e3a2f32cb1cc?q=80&w=800'],
    status: 'active',
    createdAt: new Date().toISOString(),
  },

  // FLACONS
  {
    id: 'f1',
    type: 'flacon',
    nameFR: 'Flacon Classique Transparent',
    nameAR: 'قارورة كلاسيكية شفافة',
    descriptionFR: 'Flacon en verre épais, bouchon doré. Design intemporel et élégant.',
    descriptionAR: 'قارورة زجاج سميك، سدادة ذهبية. تصميم خالد وأنيق.',
    categoryId: 'c1',
    tagIds: ['t1'],
    images: ['https://images.unsplash.com/photo-1592914610354-fd354ea45e48?q=80&w=800'],
    status: 'active',
    createdAt: new Date().toISOString(),
    variants: [
      { id: 'fv1', size: '30ml', color: '#FFFFFF', shape: 'Carré', price: 350, stock: 200 },
      { id: 'fv2', size: '50ml', color: '#FFFFFF', shape: 'Carré', price: 450, stock: 150 },
      { id: 'fv3', size: '100ml', color: '#FFFFFF', shape: 'Carré', price: 600, stock: 100 },
    ]
  },
  {
    id: 'f2',
    type: 'flacon',
    nameFR: 'Flacon Luxe Noir Atomiseur',
    nameAR: 'قارورة فخمة سوداء مع بخاخ',
    descriptionFR: 'Verre teinté noir mat avec atomiseur doré. L\'élégance absolue.',
    descriptionAR: 'زجاج ملون بالأسود المات مع بخاخ ذهبي. الأناقة المطلقة.',
    categoryId: 'c1',
    tagIds: ['t2', 't3'],
    images: ['https://images.unsplash.com/photo-1583209814683-c023dd293cc6?q=80&w=800'],
    status: 'active',
    createdAt: new Date().toISOString(),
    variants: [
      { id: 'fv4', size: '30ml', color: '#1A1A1A', shape: 'Rond', price: 550, stock: 80 },
      { id: 'fv5', size: '50ml', color: '#1A1A1A', shape: 'Rond', price: 750, stock: 60 },
      { id: 'fv6', size: '100ml', color: '#1A1A1A', shape: 'Rond', price: 950, stock: 40 },
    ]
  },
  {
    id: 'f3',
    type: 'flacon',
    nameFR: 'Flacon Oriental Gravé',
    nameAR: 'قارورة شرقية منقوشة',
    descriptionFR: 'Flacon en verre épais avec motifs orientaux gravés.',
    descriptionAR: 'قارورة زجاج سميك بنقوش شرقية. سدادة معدنية ذهبية منحوتة.',
    categoryId: 'c1',
    tagIds: ['t3'],
    images: ['https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?q=80&w=800'],
    status: 'active',
    createdAt: new Date().toISOString(),
    variants: [
      { id: 'fv8', size: '50ml', color: '#C9A84C', shape: 'Octogonal', price: 890, stock: 50 },
      { id: 'fv9', size: '100ml', color: '#C9A84C', shape: 'Octogonal', price: 1200, stock: 30 },
    ]
  },
  {
    id: 'f4',
    type: 'flacon',
    nameFR: 'Mini Flacon Voyage',
    nameAR: 'قارورة ميني للسفر',
    descriptionFR: 'Format de voyage pratique, parfait pour les petites commandes ou cadeaux.',
    descriptionAR: 'حجم سفر عملي، مثالي للطلبات الصغيرة أو الهدايا.',
    categoryId: 'c1',
    tagIds: ['t1', 't2'],
    images: ['https://images.unsplash.com/photo-1594035910387-fea477262dc0?q=80&w=800'],
    status: 'active',
    createdAt: new Date().toISOString(),
    variants: [
      { id: 'fv12', size: '5ml', color: '#FFFFFF', shape: 'Cylindrique', price: 180, stock: 500 },
    ]
  },
  {
    id: 'f5',
    type: 'flacon',
    nameFR: 'Flacon Carré Élégant',
    nameAR: 'قارورة مربعة أنيقة',
    descriptionFR: 'Design géométrique épuré. Disponible en plusieurs coloris tendance.',
    descriptionAR: 'تصميم هندسي راقٍ. متوفر بعدة ألوان عصرية.',
    categoryId: 'c1',
    tagIds: ['t2'],
    images: ['https://images.unsplash.com/photo-1592947945242-69312358628b?q=80&w=800'],
    status: 'active',
    createdAt: new Date().toISOString(),
    variants: [
      { id: 'fv16', size: '30ml', color: '#FFFFFF', shape: 'Carré', price: 420, stock: 120 },
    ]
  },
  {
    id: 'f6',
    type: 'flacon',
    nameFR: 'Flacon Goutte Arabesque',
    nameAR: 'قارورة قطرة عربسك',
    descriptionFR: 'Forme goutte avec motifs arabesques, inspiration orientale pure.',
    descriptionAR: 'شكل قطرة بنقوش أرابيسك، إلهام شرقي أصيل.',
    categoryId: 'c1',
    tagIds: ['t3', 't1'],
    images: ['https://images.unsplash.com/photo-1616984748472-de362243dccd?q=80&w=800'],
    status: 'active',
    createdAt: new Date().toISOString(),
    variants: [
      { id: 'fv21', size: '50ml', color: '#C9A84C', shape: 'Goutte', price: 720, stock: 45 },
    ]
  },
  {
    id: 'f7',
    type: 'flacon',
    nameFR: 'Flacon Roll-on Pratique',
    nameAR: 'قارورة رول أون عملية',
    descriptionFR: 'Roll-on en verre pour application directe. Idéal pour les huiles de parfum.',
    descriptionAR: 'رول أون زجاجي للتطبيق المباشر. مثالي لزيوت العطور.',
    categoryId: 'c1',
    tagIds: ['t1', 't2'],
    images: ['https://images.unsplash.com/photo-1590736704728-f4730bb30770?q=80&w=800'],
    status: 'active',
    createdAt: new Date().toISOString(),
    variants: [
      { id: 'fv25', size: '6ml', color: '#FFFFFF', shape: 'Roll-on', price: 150, stock: 600 },
    ]
  },
  {
    id: 'f8',
    type: 'flacon',
    nameFR: 'Flacon Prestige Grande Capacité',
    nameAR: 'قارورة بريستيج كبيرة السعة',
    descriptionFR: 'Pour les professionnels exigeants. Verre épais, bouchon métal luxueux.',
    descriptionAR: 'للمحترفين المتطلبين. زجاج سميك، سدادة معدنية فاخرة.',
    categoryId: 'c1',
    tagIds: ['t3'],
    images: ['https://images.unsplash.com/photo-1583209814683-c023dd293cc6?q=80&w=800'],
    status: 'active',
    createdAt: new Date().toISOString(),
    variants: [
      { id: 'fv29', size: '100ml', color: '#FFFFFF', shape: 'Carré Biseauté', price: 1100, stock: 25 },
    ]
  },
];

export const customers: Customer[] = [
  { id: 'cu1', firstName: 'Mohammed', lastName: 'Benali', shopName: 'Parfumerie El Nour', phoneNumber: '0550123456', wilaya: 'Alger', commune: 'Bab El Oued', status: 'active', joinedAt: '2025-03-15' },
  { id: 'cu2', firstName: 'Fatima', lastName: 'Bouzidi', shopName: 'Boutic Zahra', phoneNumber: '0661234567', wilaya: 'Oran', commune: 'Bir El Djir', status: 'active', joinedAt: '2025-04-02' },
];

export const orders: Order[] = [
  {
    id: 'o1', orderNumber: 'AM-000001', customerId: 'cu1',
    items: [
      { productId: 'p1', quantity: 500, unitPrice: 850, productNameAR: 'وردة الطائف', productNameFR: 'Rose du Taif' },
    ],
    total: 425000, amountPaid: 425000, paymentStatus: 'paid',
    status: 'delivered', createdAt: '2026-03-15', updatedAt: '2026-03-15'
  },
];
